# Auto-generated by matugen from the current wallpaper — do not hand-edit.
set -g fish_color_normal dde4e4
set -g fish_color_command 80d4db
set -g fish_color_param dde4e4
set -g fish_color_keyword 80d4db
set -g fish_color_quote b7c7ea
set -g fish_color_redirection dde4e4
set -g fish_color_end 899393
set -g fish_color_error ffb4ab
set -g fish_color_comment 899393
set -g fish_color_autosuggestion 899393
set -g fish_color_selection --background=80d4db
set -g fish_color_search_match --background=80d4db
set -g fish_color_operator 80d4db
set -g fish_color_cancel ffb4ab
set -g fish_pager_color_prefix 80d4db
set -g fish_pager_color_completion dde4e4
set -g fish_pager_color_description 899393
set -g fish_pager_color_selected_background --background=80d4db

# eza (used by `ll`, see fish/functions/ll.fish) doesn't read fish_color_* —
# it needs its own EZA_COLORS env var, truecolor form "38;2;R;G;B".
set -gx EZA_COLORS "di=1;38;2;128;212;219"
