# Auto-generated by matugen from the current wallpaper — do not hand-edit.
set -g fish_color_normal dee3e6
set -g fish_color_command 85d2e8
set -g fish_color_param dee3e6
set -g fish_color_keyword 85d2e8
set -g fish_color_quote c0c4eb
set -g fish_color_redirection dee3e6
set -g fish_color_end 899295
set -g fish_color_error ffb4ab
set -g fish_color_comment 899295
set -g fish_color_autosuggestion 899295
set -g fish_color_selection --background=85d2e8
set -g fish_color_search_match --background=85d2e8
set -g fish_color_operator 85d2e8
set -g fish_color_cancel ffb4ab
set -g fish_pager_color_prefix 85d2e8
set -g fish_pager_color_completion dee3e6
set -g fish_pager_color_description 899295
set -g fish_pager_color_selected_background --background=85d2e8

# eza (used by `ll`, see fish/functions/ll.fish) doesn't read fish_color_* —
# it needs its own EZA_COLORS env var, truecolor form "38;2;R;G;B".
set -gx EZA_COLORS "di=1;38;2;133;210;232"
