# Auto-generated by matugen from the current wallpaper — do not hand-edit.
set -g fish_color_normal e1e4da
set -g fish_color_command a7d293
set -g fish_color_param e1e4da
set -g fish_color_keyword a7d293
set -g fish_color_quote a0cfd1
set -g fish_color_redirection e1e4da
set -g fish_color_end 8d9387
set -g fish_color_error ffb4ab
set -g fish_color_comment 8d9387
set -g fish_color_autosuggestion 8d9387
set -g fish_color_selection --background=a7d293
set -g fish_color_search_match --background=a7d293
set -g fish_color_operator a7d293
set -g fish_color_cancel ffb4ab
set -g fish_pager_color_prefix a7d293
set -g fish_pager_color_completion e1e4da
set -g fish_pager_color_description 8d9387
set -g fish_pager_color_selected_background --background=a7d293

# eza (used by `ll`, see fish/functions/ll.fish) doesn't read fish_color_* —
# it needs its own EZA_COLORS env var, truecolor form "38;2;R;G;B".
set -gx EZA_COLORS "di=1;38;2;167;210;147"
