# Auto-generated by matugen from the current wallpaper — do not hand-edit.
set -g fish_color_normal {{colors.on_surface.default.hex_stripped}}
set -g fish_color_command {{colors.primary.default.hex_stripped}}
set -g fish_color_param {{colors.on_surface.default.hex_stripped}}
set -g fish_color_keyword {{colors.primary.default.hex_stripped}}
set -g fish_color_quote {{colors.tertiary.default.hex_stripped}}
set -g fish_color_redirection {{colors.on_surface.default.hex_stripped}}
set -g fish_color_end {{colors.outline.default.hex_stripped}}
set -g fish_color_error {{colors.error.default.hex_stripped}}
set -g fish_color_comment {{colors.outline.default.hex_stripped}}
set -g fish_color_autosuggestion {{colors.outline.default.hex_stripped}}
set -g fish_color_selection --background={{colors.primary.default.hex_stripped}}
set -g fish_color_search_match --background={{colors.primary.default.hex_stripped}}
set -g fish_color_operator {{colors.primary.default.hex_stripped}}
set -g fish_color_cancel {{colors.error.default.hex_stripped}}
set -g fish_pager_color_prefix {{colors.primary.default.hex_stripped}}
set -g fish_pager_color_completion {{colors.on_surface.default.hex_stripped}}
set -g fish_pager_color_description {{colors.outline.default.hex_stripped}}
set -g fish_pager_color_selected_background --background={{colors.primary.default.hex_stripped}}

# eza (used by `ll`, see fish/functions/ll.fish) doesn't read fish_color_* —
# it needs its own EZA_COLORS env var, truecolor form "38;2;R;G;B".
set -gx EZA_COLORS "di=1;38;2;{{colors.primary.default.hex | to_color | format: "rgb" | replace: "rgb(", "" | replace: ")", "" | replace: ", ", ";"}}"
